// Auto-generated list of supported currencies and their associated countries
export const CURRENCIES = [
  { code: 'AED', country: 'Émirats arabes unis', label: 'Émirats arabes unis (Dirham des Émirats arabes unis, AED)' },
  { code: 'AFN', country: 'Afghanistan', label: 'Afghanistan (Afghani afghan, AFN)' },
  { code: 'ALL', country: 'Albanie', label: 'Albanie (Lek albanais, ALL)' },
  { code: 'AMD', country: 'Arménie', label: 'Arménie (Dram arménien, AMD)' },
  { code: 'ANG', country: 'Curaçao', label: 'Curaçao (Florin antillais, ANG)' },
  { code: 'AOA', country: 'Angola', label: 'Angola (Kwanza angolais, AOA)' },
  { code: 'ARS', country: 'Argentine', label: 'Argentine (Peso argentin, ARS)' },
  { code: 'AUD', country: 'Australie', label: 'Australie (Dollar australien, AUD)' },
  { code: 'AWG', country: 'Aruba', label: 'Aruba (Florin arubais, AWG)' },
  { code: 'AZN', country: 'Azerbaïdjan', label: 'Azerbaïdjan (Manat azéri, AZN)' },
  { code: 'BAM', country: 'Bosnie-Herzégovine', label: 'Bosnie-Herzégovine (Mark convertible bosniaque, BAM)' },
  { code: 'BBD', country: 'Barbade', label: 'Barbade (Dollar barbadien, BBD)' },
  { code: 'BDT', country: 'Bangladesh', label: 'Bangladesh (Taka bangladeshi, BDT)' },
  { code: 'BGN', country: 'Bulgarie', label: 'Bulgarie (Lev bulgare, BGN)' },
  { code: 'BHD', country: 'Bahreïn', label: 'Bahreïn (Dinar bahreïni, BHD)' },
  { code: 'BIF', country: 'Burundi', label: 'Burundi (Franc burundais, BIF)' },
  { code: 'BMD', country: 'Bermudes', label: 'Bermudes (Dollar bermudien, BMD)' },
  { code: 'BND', country: 'Brunei', label: 'Brunei (Dollar brunéien, BND)' },
  { code: 'BOB', country: 'Bolivie', label: 'Bolivie (Boliviano bolivien, BOB)' },
  { code: 'BRL', country: 'Brésil', label: 'Brésil (Réal brésilien, BRL)' },
  { code: 'BSD', country: 'Bahamas', label: 'Bahamas (Dollar bahaméen, BSD)' },
  { code: 'BTN', country: 'Bhoutan', label: 'Bhoutan (Ngultrum bouthanais, BTN)' },
  { code: 'BWP', country: 'Botswana', label: 'Botswana (Pula botswanais, BWP)' },
  { code: 'BYN', country: 'Biélorussie', label: 'Biélorussie (Rouble biélorusse, BYN)' },
  { code: 'BZD', country: 'Belize', label: 'Belize (Dollar bélizéen, BZD)' },
  { code: 'CAD', country: 'Canada', label: 'Canada (Dollar canadien, CAD)' },
  { code: 'CDF', country: 'Congo-Kinshasa', label: 'Congo-Kinshasa (Franc congolais, CDF)' },
  { code: 'CHF', country: 'Suisse', label: 'Suisse (Franc suisse, CHF)' },
  { code: 'CLF', country: 'Chili', label: 'Chili (Unité d’investissement chilienne, CLF)' },
  { code: 'CLP', country: 'Chili', label: 'Chili (Peso chilien, CLP)' },
  { code: 'CNH', country: 'Chine', label: 'Chine (Yuan chinois (zone extracôtière), CNH)' },
  { code: 'CNY', country: 'Chine', label: 'Chine (Yuan renminbi chinois, CNY)' },
  { code: 'COP', country: 'Colombie', label: 'Colombie (Peso colombien, COP)' },
  { code: 'CRC', country: 'Costa Rica', label: 'Costa Rica (Colón costaricain, CRC)' },
  { code: 'CUP', country: 'Cuba', label: 'Cuba (Peso cubain, CUP)' },
  { code: 'CVE', country: 'Cap-Vert', label: 'Cap-Vert (Escudo capverdien, CVE)' },
  { code: 'CZK', country: 'Tchéquie', label: 'Tchéquie (Couronne tchèque, CZK)' },
  { code: 'DJF', country: 'Djibouti', label: 'Djibouti (Franc djiboutien, DJF)' },
  { code: 'DKK', country: 'Danemark', label: 'Danemark (Couronne danoise, DKK)' },
  { code: 'DOP', country: 'République dominicaine', label: 'République dominicaine (Peso dominicain, DOP)' },
  { code: 'DZD', country: 'Algérie', label: 'Algérie (Dinar algérien, DZD)' },
  { code: 'EGP', country: 'Égypte', label: 'Égypte (Livre égyptienne, EGP)' },
  { code: 'ERN', country: 'Érythrée', label: 'Érythrée (Nafka érythréen, ERN)' },
  { code: 'ETB', country: 'Éthiopie', label: 'Éthiopie (Birr éthiopien, ETB)' },
  { code: 'FJD', country: 'Fidji', label: 'Fidji (Dollar fidjien, FJD)' },
  { code: 'FKP', country: 'Îles Malouines', label: 'Îles Malouines (Livre des îles Malouines, FKP)' },
  { code: 'FOK', country: 'Îles Féroé', label: 'Îles Féroé (FOK, FOK)' },
  { code: 'GBP', country: 'Royaume-Uni', label: 'Royaume-Uni (Livre sterling, GBP)' },
  { code: 'GEL', country: 'Géorgie', label: 'Géorgie (Lari géorgien, GEL)' },
  { code: 'GGP', country: 'Guernesey', label: 'Guernesey (GGP, GGP)' },
  { code: 'GHS', country: 'Ghana', label: 'Ghana (Cédi ghanéen, GHS)' },
  { code: 'GIP', country: 'Gibraltar', label: 'Gibraltar (Livre de Gibraltar, GIP)' },
  { code: 'GMD', country: 'Gambie', label: 'Gambie (Dalasi gambien, GMD)' },
  { code: 'GNF', country: 'Guinée', label: 'Guinée (Franc guinéen, GNF)' },
  { code: 'GTQ', country: 'Guatemala', label: 'Guatemala (Quetzal guatémaltèque, GTQ)' },
  { code: 'GYD', country: 'Guyana', label: 'Guyana (Dollar du Guyana, GYD)' },
  { code: 'HKD', country: 'R.A.S. chinoise de Hong Kong', label: 'R.A.S. chinoise de Hong Kong (Dollar de Hong Kong, HKD)' },
  { code: 'HNL', country: 'Honduras', label: 'Honduras (Lempira hondurien, HNL)' },
  { code: 'HRK', country: 'Croatie', label: 'Croatie (Kuna croate, HRK)' },
  { code: 'HTG', country: 'Haïti', label: 'Haïti (Gourde haïtienne, HTG)' },
  { code: 'HUF', country: 'Hongrie', label: 'Hongrie (Forint hongrois, HUF)' },
  { code: 'IDR', country: 'Indonésie', label: 'Indonésie (Roupie indonésienne, IDR)' },
  { code: 'ILS', country: 'Israël', label: 'Israël (Nouveau shekel israélien, ILS)' },
  { code: 'IMP', country: 'Île de Man', label: 'Île de Man (IMP, IMP)' },
  { code: 'INR', country: 'Inde', label: 'Inde (Roupie indienne, INR)' },
  { code: 'IQD', country: 'Irak', label: 'Irak (Dinar irakien, IQD)' },
  { code: 'IRR', country: 'Iran', label: 'Iran (Riyal iranien, IRR)' },
  { code: 'ISK', country: 'Islande', label: 'Islande (Couronne islandaise, ISK)' },
  { code: 'JEP', country: 'Jersey', label: 'Jersey (JEP, JEP)' },
  { code: 'JMD', country: 'Jamaïque', label: 'Jamaïque (Dollar jamaïcain, JMD)' },
  { code: 'JOD', country: 'Jordanie', label: 'Jordanie (Dinar jordanien, JOD)' },
  { code: 'JPY', country: 'Japon', label: 'Japon (Yen japonais, JPY)' },
  { code: 'KES', country: 'Kenya', label: 'Kenya (Shilling kényan, KES)' },
  { code: 'KGS', country: 'Kirghizstan', label: 'Kirghizstan (Som kirghize, KGS)' },
  { code: 'KHR', country: 'Cambodge', label: 'Cambodge (Riel cambodgien, KHR)' },
  { code: 'KID', country: 'Kiribati', label: 'Kiribati (KID, KID)' },
  { code: 'KMF', country: 'Comores', label: 'Comores (Franc comorien, KMF)' },
  { code: 'KRW', country: 'Corée du Sud', label: 'Corée du Sud (Won sud-coréen, KRW)' },
  { code: 'KWD', country: 'Koweït', label: 'Koweït (Dinar koweïtien, KWD)' },
  { code: 'KYD', country: 'Îles Caïmans', label: 'Îles Caïmans (Dollar des îles Caïmans, KYD)' },
  { code: 'KZT', country: 'Kazakhstan', label: 'Kazakhstan (Tenge kazakh, KZT)' },
  { code: 'LAK', country: 'Laos', label: 'Laos (Kip laotien, LAK)' },
  { code: 'LBP', country: 'Liban', label: 'Liban (Livre libanaise, LBP)' },
  { code: 'LKR', country: 'Sri Lanka', label: 'Sri Lanka (Roupie srilankaise, LKR)' },
  { code: 'LRD', country: 'Liberia', label: 'Liberia (Dollar libérien, LRD)' },
  { code: 'LSL', country: 'Lesotho', label: 'Lesotho (Loti lesothan, LSL)' },
  { code: 'LYD', country: 'Libye', label: 'Libye (Dinar libyen, LYD)' },
  { code: 'MAD', country: 'Maroc', label: 'Maroc (Dirham marocain, MAD)' },
  { code: 'MDL', country: 'Moldavie', label: 'Moldavie (Leu moldave, MDL)' },
  { code: 'MGA', country: 'Madagascar', label: 'Madagascar (Ariary malgache, MGA)' },
  { code: 'MKD', country: 'Macédoine du Nord', label: 'Macédoine du Nord (Denar macédonien, MKD)' },
  { code: 'MMK', country: 'Myanmar (Birmanie)', label: 'Myanmar (Birmanie) (Kyat myanmarais, MMK)' },
  { code: 'MNT', country: 'Mongolie', label: 'Mongolie (Tugrik mongol, MNT)' },
  { code: 'MOP', country: 'R.A.S. chinoise de Macao', label: 'R.A.S. chinoise de Macao (Pataca macanaise, MOP)' },
  { code: 'MRU', country: 'Mauritanie', label: 'Mauritanie (Ouguiya mauritanien, MRU)' },
  { code: 'MUR', country: 'Maurice', label: 'Maurice (Roupie mauricienne, MUR)' },
  { code: 'MVR', country: 'Maldives', label: 'Maldives (Rufiyaa maldivienne, MVR)' },
  { code: 'MWK', country: 'Malawi', label: 'Malawi (Kwacha malawite, MWK)' },
  { code: 'MXN', country: 'Mexique', label: 'Mexique (Peso mexicain, MXN)' },
  { code: 'MYR', country: 'Malaisie', label: 'Malaisie (Ringgit malais, MYR)' },
  { code: 'MZN', country: 'Mozambique', label: 'Mozambique (Metical mozambicain, MZN)' },
  { code: 'NAD', country: 'Namibie', label: 'Namibie (Dollar namibien, NAD)' },
  { code: 'NGN', country: 'Nigeria', label: 'Nigeria (Naira nigérian, NGN)' },
  { code: 'NIO', country: 'Nicaragua', label: 'Nicaragua (Córdoba oro nicaraguayen, NIO)' },
  { code: 'NOK', country: 'Norvège', label: 'Norvège (Couronne norvégienne, NOK)' },
  { code: 'NPR', country: 'Népal', label: 'Népal (Roupie népalaise, NPR)' },
  { code: 'NZD', country: 'Nouvelle-Zélande', label: 'Nouvelle-Zélande (Dollar néo-zélandais, NZD)' },
  { code: 'OMR', country: 'Oman', label: 'Oman (Riyal omanais, OMR)' },
  { code: 'PAB', country: 'Panama', label: 'Panama (Balboa panaméen, PAB)' },
  { code: 'PEN', country: 'Pérou', label: 'Pérou (Sol péruvien, PEN)' },
  { code: 'PGK', country: 'Papouasie-Nouvelle-Guinée', label: 'Papouasie-Nouvelle-Guinée (Kina papouan-néo-guinéen, PGK)' },
  { code: 'PHP', country: 'Philippines', label: 'Philippines (Peso philippin, PHP)' },
  { code: 'PKR', country: 'Pakistan', label: 'Pakistan (Roupie pakistanaise, PKR)' },
  { code: 'PLN', country: 'Pologne', label: 'Pologne (Zloty polonais, PLN)' },
  { code: 'PYG', country: 'Paraguay', label: 'Paraguay (Guaraní paraguayen, PYG)' },
  { code: 'QAR', country: 'Qatar', label: 'Qatar (Riyal qatari, QAR)' },
  { code: 'RON', country: 'Roumanie', label: 'Roumanie (Leu roumain, RON)' },
  { code: 'RSD', country: 'Serbie', label: 'Serbie (Dinar serbe, RSD)' },
  { code: 'RUB', country: 'Russie', label: 'Russie (Rouble russe, RUB)' },
  { code: 'RWF', country: 'Rwanda', label: 'Rwanda (Franc rwandais, RWF)' },
  { code: 'SAR', country: 'Arabie saoudite', label: 'Arabie saoudite (Riyal saoudien, SAR)' },
  { code: 'SBD', country: 'Îles Salomon', label: 'Îles Salomon (Dollar des îles Salomon, SBD)' },
  { code: 'SCR', country: 'Seychelles', label: 'Seychelles (Roupie des Seychelles, SCR)' },
  { code: 'SDG', country: 'Soudan', label: 'Soudan (Livre soudanaise, SDG)' },
  { code: 'SEK', country: 'Suède', label: 'Suède (Couronne suédoise, SEK)' },
  { code: 'SGD', country: 'Singapour', label: 'Singapour (Dollar de Singapour, SGD)' },
  { code: 'SHP', country: 'Sainte-Hélène', label: 'Sainte-Hélène (Livre de Sainte-Hélène, SHP)' },
  { code: 'SLE', country: 'Sierra Leone', label: 'Sierra Leone (Leone sierra-léonais, SLE)' },
  { code: 'SLL', country: 'Sierra Leone', label: 'Sierra Leone (Leone sierra-léonais (1964—2022), SLL)' },
  { code: 'SOS', country: 'Somalie', label: 'Somalie (Shilling somalien, SOS)' },
  { code: 'SRD', country: 'Suriname', label: 'Suriname (Dollar surinamais, SRD)' },
  { code: 'SSP', country: 'Soudan du Sud', label: 'Soudan du Sud (Livre sud-soudanaise, SSP)' },
  { code: 'STN', country: 'Sao Tomé-et-Principe', label: 'Sao Tomé-et-Principe (Dobra santoméen, STN)' },
  { code: 'SYP', country: 'Syrie', label: 'Syrie (Livre syrienne, SYP)' },
  { code: 'SZL', country: 'Eswatini', label: 'Eswatini (Lilangeni swazi, SZL)' },
  { code: 'THB', country: 'Thaïlande', label: 'Thaïlande (Baht thaïlandais, THB)' },
  { code: 'TJS', country: 'Tadjikistan', label: 'Tadjikistan (Somoni tadjik, TJS)' },
  { code: 'TMT', country: 'Turkménistan', label: 'Turkménistan (Nouveau manat turkmène, TMT)' },
  { code: 'TND', country: 'Tunisie', label: 'Tunisie (Dinar tunisien, TND)' },
  { code: 'TOP', country: 'Tonga', label: 'Tonga (Pa’anga tongan, TOP)' },
  { code: 'TRY', country: 'Turquie', label: 'Turquie (Livre turque, TRY)' },
  { code: 'TTD', country: 'Trinité-et-Tobago', label: 'Trinité-et-Tobago (Dollar de Trinité-et-Tobago, TTD)' },
  { code: 'TVD', country: 'Tuvalu', label: 'Tuvalu (TVD, TVD)' },
  { code: 'TWD', country: 'Taïwan', label: 'Taïwan (Nouveau dollar taïwanais, TWD)' },
  { code: 'TZS', country: 'Tanzanie', label: 'Tanzanie (Shilling tanzanien, TZS)' },
  { code: 'UAH', country: 'Ukraine', label: 'Ukraine (Hryvnia ukrainienne, UAH)' },
  { code: 'UGX', country: 'Ouganda', label: 'Ouganda (Shilling ougandais, UGX)' },
  { code: 'USD', country: 'États-Unis', label: 'États-Unis (Dollar des États-Unis, USD)' },
  { code: 'UYU', country: 'Uruguay', label: 'Uruguay (Peso uruguayen, UYU)' },
  { code: 'UZS', country: 'Ouzbékistan', label: 'Ouzbékistan (Sum ouzbek, UZS)' },
  { code: 'VES', country: 'Venezuela', label: 'Venezuela (Bolivar vénézuélien, VES)' },
  { code: 'VND', country: 'Viêt Nam', label: 'Viêt Nam (Dông vietnamien, VND)' },
  { code: 'VUV', country: 'Vanuatu', label: 'Vanuatu (Vatu vanuatuan, VUV)' },
  { code: 'WST', country: 'Samoa', label: 'Samoa (Tala samoan, WST)' },
  { code: 'XAF', country: 'CEMAC (Afrique Centrale)', label: 'CEMAC (Afrique Centrale) (Franc CFA (BEAC), XAF)' },
  { code: 'XCD', country: 'OECS (Caraïbes orientales)', label: 'OECS (Caraïbes orientales) (Dollar des Caraïbes orientales, XCD)' },
  { code: 'XCG', country: 'XCG', label: 'XCG (Florin caribéen, XCG)' },
  { code: 'XDR', country: 'XDR', label: 'XDR (Droit de tirage spécial, XDR)' },
  { code: 'XOF', country: 'UEMOA (Afrique de l\'Ouest)', label: 'UEMOA (Afrique de l\'Ouest) (Franc CFA (BCEAO), XOF)' },
  { code: 'XPF', country: 'Pacifique français', label: 'Pacifique français (Franc CFP, XPF)' },
  { code: 'YER', country: 'Yémen', label: 'Yémen (Riyal yéménite, YER)' },
  { code: 'ZAR', country: 'Afrique du Sud', label: 'Afrique du Sud (Rand sud-africain, ZAR)' },
  { code: 'ZMW', country: 'Zambie', label: 'Zambie (Kwacha zambien, ZMW)' },
  { code: 'ZWG', country: 'Zimbabwe', label: 'Zimbabwe (ZWG, ZWG)' },
  { code: 'ZWL', country: 'Zimbabwe', label: 'Zimbabwe (Dollar zimbabwéen (2009), ZWL)' },
];
